services:
  telegram_instagram_downloader_bot:
    build: .
    container_name: telegram_instagram_downloader_bot
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - RAPIDAPI_KEY=${RAPIDAPI_KEY}
      - ALLOWED_USERS=${ALLOWED_USERS}
    volumes:
      - ./data:/app/data  # Persist SQLite database
    restart: always
